export const COLUMNS = 'abcdefgh'.split('');

export const chessboardDefaultProps = {
  animationDuration: 300,
  arePiecesDraggable: true,
  boardOrientation: 'white',
  boardWidth: 560,
  customBoardStyle: {},
  customDarkSquareStyle: { backgroundColor: '#B58863' },
  customDndBackend: undefined,
  customDndBackendOptions: undefined,
  customDropSquareStyle: { boxShadow: 'inset 0 0 1px 6px rgba(255,255,255,0.75)' },
  customLightSquareStyle: { backgroundColor: '#F0D9B5' },
  customPieces: {},
  customSquareStyles: {},
  dropOffBoardAction: 'snapback',
  id: 0,
  isDraggablePiece: () => true,
  getPositionObject: () => {},
  onDragOverSquare: () => {},
  onMouseOutSquare: () => {},
  onMouseOverSquare: () => {},
  onMoveComplete: () => {},
  onPieceClick: () => {},
  onPieceDragBegin: () => {},
  onPieceDragEnd: () => {},
  onPieceDrop: () => true,
  onSquareClick: () => {},
  position: 'start',
  showBoardNotation: true,
  // showSparePieces: false,
  snapToCursor: true
};
